baseURL: "https://petevieira.github.io/"
languageCode: "en-us"
title: "Makotori"
theme: "cupper-hugo-theme"
params:
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).
  hideHeaderLinks: false
  darkThemeAsDefault: false
  search: true
  toc: true
  custom_js: ["js/custom.js"]
sectionPagesMenu: "main"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4

